import type { Module } from '@/types'

export const MODULES: Module[] = [
  {
    id: 'nals-monitor',
    name: 'NALS Monitor Pro',
    tagline: 'Reanimación Neonatal en Tiempo Real',
    description: 'Monitor completo de reanimación neonatal con cronómetro automático, metrónomo 3:1, registro de drogas, escalas APGAR/Sarnat, gasimetría y epicrisis profesional.',
    category: 'Neonatología',
    color: '#3b82f6',
    icon: '🫀',
    version: '19.5',
    status: 'active',
    features: [
      'Cronómetro y metrónomo 3:1 automático',
      'Registro de adrenalina con bloqueo de seguridad',
      'Escalas APGAR y Sarnat integradas',
      'Gasimetría arterial con historial',
      'Algoritmo NRP interactivo',
      'Epicrisis profesional exportable',
      'Guía vocal en español',
      'MR. SOPA y causas reversibles',
    ],
  },
  {
    id: 'pals-monitor',
    name: 'PALS Monitor',
    tagline: 'Soporte Vital Avanzado Pediátrico',
    description: 'Monitor de reanimación pediátrica con protocolos PALS actualizados, cálculo de dosis por peso y desfibrilación guiada.',
    category: 'Pediatría',
    color: '#8b5cf6',
    icon: '🩺',
    version: '2.0',
    status: 'active',
    features: ['Protocolos PALS 2025', 'Calculadora de dosis pediátricas', 'Guía de desfibrilación', 'Timer de ciclos', 'Registro farmacológico', 'Informe post-evento'],
  },
  {
    id: 'acls-monitor',
    name: 'ACLS Monitor',
    tagline: 'Soporte Vital Cardiovascular Avanzado',
    description: 'Monitor de reanimación cardiovascular avanzada con protocolos ACLS actualizados, ritmos desfibrilables y no desfibrilables, y registro completo de eventos.',
    category: 'Cardiología',
    color: '#ef4444',
    icon: '🫀',
    version: '1.0',
    status: 'active',
    features: ['Protocolos ACLS 2025', 'Ritmos desfibrilables/no desfibrilables', 'Cálculo de dosis adulto', 'Timer de ciclos 2 min', 'Registro de descargas', 'Epicrisis exportable'],
  },
  {
    id: 'uci-dashboard',
    name: 'UCI Central',
    tagline: 'Dashboard de Monitoreo Intensivo',
    description: 'Panel centralizado para UCI neonatal y pediátrica con monitoreo multi-cama y alertas en tiempo real.',
    category: 'Cuidado Intensivo',
    color: '#06b6d4',
    icon: '📊',
    version: '1.0',
    status: 'coming_soon',
    features: ['Monitoreo multi-cama', 'Alertas configurables', 'Escalas de gravedad', 'Tendencias vitales', 'Ventilación mecánica', 'Reportes de turno'],
  },
  {
    id: 'pharma-calc',
    name: 'PharmaCalc Neo',
    tagline: 'Calculadora Farmacológica Neonatal',
    description: 'Calculadora avanzada de dosis neonatales con verificación de rangos terapéuticos e interacciones.',
    category: 'Farmacología',
    color: '#10b981',
    icon: '💊',
    version: '1.0',
    status: 'coming_soon',
    features: ['Base de fármacos neonatales', 'Cálculo por peso y EG', 'Alertas terapéuticas', 'Infusión continua', 'Interacciones', 'Exportar prescripciones'],
  },
  {
    id: 'clinical-log',
    name: 'Historia Clínica Digital',
    tagline: 'Registro Clínico Estructurado',
    description: 'Historia clínica digital con plantillas neonatales, evoluciones SOAP y firma electrónica.',
    category: 'Registros',
    color: '#f59e0b',
    icon: '📋',
    version: '1.0',
    status: 'coming_soon',
    features: ['Plantillas neonatales', 'Evoluciones SOAP', 'Firma electrónica', 'Export HL7/FHIR', 'Auditoría', 'Multi-dispositivo'],
  },
  {
    id: 'lab-tracker',
    name: 'LabTrack Neo',
    tagline: 'Seguimiento de Laboratorios',
    description: 'Seguimiento y análisis de resultados de laboratorio neonatal con tendencias y alertas de valores críticos.',
    category: 'Laboratorio',
    color: '#ec4899',
    icon: '🧪',
    version: '1.0',
    status: 'coming_soon',
    features: ['Resultados en tiempo real', 'Tendencias gráficas', 'Alertas críticas', 'Correlación clínica', 'Hemocultivos', 'Export investigación'],
  },
]

export function getModule(id: string): Module | undefined {
  return MODULES.find(m => m.id === id)
}
